package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.OAccount461;

public interface OAccount461Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.O_ACCOUNT461
     *
     * @mbg.generated Sat May 04 18:42:39 JST 2019
     */
    int insert(OAccount461 record);

	// 以下、オリジナル実装
	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OAccount461> selectAsMonth();
}