package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.ActualValueResultEntity;
import house.keep.mybatis.model.housekeeper.OAccount241;
import house.keep.mybatis.model.housekeeper.OOther;

/**
 * 口座241。
 *
 * @author Tatsuya
 *
 */
public interface OAccount241Mapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.O_ACCOUNT241
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    int insert(OAccount241 record);

	// 以下、オリジナル実装
	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OAccount241> selectAsMonth();

	/**
	 * 支払月で絞り込んだレコードを返す。
	 *
	 * @return OAccount241
	 */
	OAccount241 selectWherePaymentdateByStringDateYYMM(OAccount241 record);

	OAccount241 selectNextPaymentdate(OAccount241 record);

	List<OAccount241> selectGroupByExpenseWhereFromTo(OAccount241 record);

	List<OOther> selectGroupByExpenseWhereFromToAndDetails(OAccount241 record);

	ActualValueResultEntity selectActuaResults(OAccount241 record);

	ActualValueResultEntity selectActuaResults461(OAccount241 record);
}