package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.OFood;

/**
 * 食費。
 */
public interface OFoodMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table HOUSEKEEPER.O_FOOD
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	int insert(OFood record);

	// 以下、オリジナル実装

	/**
	 * 全レコード取得。
	 *
	 * @return List
	 */
	List<OFood> selectAll();

	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OFood> selectAsMonth();

}