package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.OGoods;

/**
 * 常駐家庭用品費。
 */
public interface OGoodsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.O_GOODS
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    int insertSelective(OGoods record);

	// 以下、オリジナル実装
	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OGoods> selectAsMonth();
}