package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.OOther;

public interface OOtherMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table HOUSEKEEPER.O_OTHER
	 *
	 * @mbg.generated Sun May 12 15:00:08 JST 2019
	 */
	int insert(OOther record);

	// 以下、オリジナル実装
	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OOther> selectAsMonth();

	/**
	 * 明細取得。
	 *
	 * @return List
	 */
	List<OOther> selectDetail(OOther record);
}