package house.keep.mybatis.dao.housekeeper;

import java.util.List;

import house.keep.mybatis.model.housekeeper.OWaste;

/**
 * 娯楽費。
 */
public interface OWasteMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.O_WASTE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    int insert(OWaste record);

	// 以下、オリジナル実装
	/**
	 * 月ごとレコード取得。
	 *
	 * @return List
	 */
	List<OWaste> selectAsMonth();
}