package house.keep.mybatis.dao.housekeeper;

import house.keep.mybatis.model.housekeeper.Money;
import house.keep.mybatis.model.housekeeper.MoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    long countByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    int deleteByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    int insert(Money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    int insertSelective(Money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    List<Money> selectByExample(MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    int updateByExampleSelective(@Param("record") Money record, @Param("example") MoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSEKEEPER.MONEY
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    int updateByExample(@Param("record") Money record, @Param("example") MoneyExample example);
}