package house.keep.mybatis.model.housekeeper;

import java.math.BigDecimal;
import java.util.Date;

public class Money {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.MONEY.INPUT_DATE
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.MONEY.AMOUNT
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.MONEY.INPUT_DATE
     *
     * @return the value of HOUSEKEEPER.MONEY.INPUT_DATE
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.MONEY.INPUT_DATE
     *
     * @param inputDate the value for HOUSEKEEPER.MONEY.INPUT_DATE
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.MONEY.AMOUNT
     *
     * @return the value of HOUSEKEEPER.MONEY.AMOUNT
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.MONEY.AMOUNT
     *
     * @param amount the value for HOUSEKEEPER.MONEY.AMOUNT
     *
     * @mbg.generated Sun Jul 07 18:21:16 JST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}