package house.keep.mybatis.model.housekeeper;

import java.math.BigDecimal;
import java.util.Date;

public class OGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_GOODS.PAYMENT_DATE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_GOODS.AMOUNT
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_GOODS.EXPENSE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    private String expense;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_GOODS.PAYMENT_DATE
     *
     * @return the value of HOUSEKEEPER.O_GOODS.PAYMENT_DATE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_GOODS.PAYMENT_DATE
     *
     * @param paymentDate the value for HOUSEKEEPER.O_GOODS.PAYMENT_DATE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_GOODS.AMOUNT
     *
     * @return the value of HOUSEKEEPER.O_GOODS.AMOUNT
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_GOODS.AMOUNT
     *
     * @param amount the value for HOUSEKEEPER.O_GOODS.AMOUNT
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_GOODS.EXPENSE
     *
     * @return the value of HOUSEKEEPER.O_GOODS.EXPENSE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public String getExpense() {
        return expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_GOODS.EXPENSE
     *
     * @param expense the value for HOUSEKEEPER.O_GOODS.EXPENSE
     *
     * @mbg.generated Wed May 01 16:53:22 JST 2019
     */
    public void setExpense(String expense) {
        this.expense = expense == null ? null : expense.trim();
    }

	// 以下、拡張カラム。
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	private Date paymentMonth;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @return the value of HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	public Date getPaymentMonth() {
		return paymentMonth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @param paymentMonth the value for HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	public void setPaymentMonth(Date paymentMonth) {
		this.paymentMonth = paymentMonth;
	}
}