package house.keep.mybatis.model.housekeeper;

import java.math.BigDecimal;
import java.util.Date;

public class OOther {

    private Date singleSheetFrom;
    private Date singleSheetTo;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_OTHER.PAYMENT_DATE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_OTHER.AMOUNT
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_OTHER.EXPENSE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    private String expense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSEKEEPER.O_OTHER.DETAIL
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_OTHER.PAYMENT_DATE
     *
     * @return the value of HOUSEKEEPER.O_OTHER.PAYMENT_DATE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_OTHER.PAYMENT_DATE
     *
     * @param paymentDate the value for HOUSEKEEPER.O_OTHER.PAYMENT_DATE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_OTHER.AMOUNT
     *
     * @return the value of HOUSEKEEPER.O_OTHER.AMOUNT
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_OTHER.AMOUNT
     *
     * @param amount the value for HOUSEKEEPER.O_OTHER.AMOUNT
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_OTHER.EXPENSE
     *
     * @return the value of HOUSEKEEPER.O_OTHER.EXPENSE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public String getExpense() {
        return expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_OTHER.EXPENSE
     *
     * @param expense the value for HOUSEKEEPER.O_OTHER.EXPENSE
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public void setExpense(String expense) {
        this.expense = expense == null ? null : expense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSEKEEPER.O_OTHER.DETAIL
     *
     * @return the value of HOUSEKEEPER.O_OTHER.DETAIL
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSEKEEPER.O_OTHER.DETAIL
     *
     * @param detail the value for HOUSEKEEPER.O_OTHER.DETAIL
     *
     * @mbg.generated Sun May 12 15:00:08 JST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

	// 以下、拡張カラム。
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	private Date paymentMonth;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @return the value of HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	public Date getPaymentMonth() {
		return paymentMonth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @param paymentMonth the value for HOUSEKEEPER.O_FOOD.PAYMENT_DATE
	 *
	 * @mbg.generated Wed May 01 11:51:11 JST 2019
	 */
	public void setPaymentMonth(Date paymentMonth) {
		this.paymentMonth = paymentMonth;
	}

	/**
	 * @return singleSheetFrom
	 */
	public Date getSingleSheetFrom() {
		return singleSheetFrom;
	}

	/**
	 * @param singleSheetFrom セットする singleSheetFrom
	 */
	public void setSingleSheetFrom(Date singleSheetFrom) {
		this.singleSheetFrom = singleSheetFrom;
	}

	/**
	 * @return singleSheetTo
	 */
	public Date getSingleSheetTo() {
		return singleSheetTo;
	}

	/**
	 * @param singleSheetTo セットする singleSheetTo
	 */
	public void setSingleSheetTo(Date singleSheetTo) {
		this.singleSheetTo = singleSheetTo;
	}
}